// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package todoRepository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Email     string             `json:"email"`
	Done      pgtype.Bool        `json:"done"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
