// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package todoRepository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteTodoById(ctx context.Context, id pgtype.UUID) (int64, error)
	GetTodos(ctx context.Context) ([]Todo, error)
	InsertTodo(ctx context.Context, arg InsertTodoParams) (Todo, error)
	UpdateTodoCompletedById(ctx context.Context, id pgtype.UUID) (int64, error)
}

var _ Querier = (*Queries)(nil)
