// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package todoRepository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTodoById = `-- name: DeleteTodoById :execrows
DELETE FROM todos
WHERE id = $1
`

func (q *Queries) DeleteTodoById(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTodoById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTodos = `-- name: GetTodos :many
SELECT id, title, email, done, created_at, updated_at
FROM todos
`

func (q *Queries) GetTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Email,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTodo = `-- name: InsertTodo :one
INSERT INTO todos (title,email)
VALUES ($1,$2)
RETURNING id, title, email, done, created_at, updated_at
`

type InsertTodoParams struct {
	Title string `json:"title"`
	Email string `json:"email"`
}

func (q *Queries) InsertTodo(ctx context.Context, arg InsertTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, insertTodo, arg.Title, arg.Email)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Email,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoCompletedById = `-- name: UpdateTodoCompletedById :execrows
UPDATE todos
SET done = true
WHERE id = $1
`

func (q *Queries) UpdateTodoCompletedById(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, updateTodoCompletedById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
